spring.datasource.url=jdbc:postgresql://shinkansen.proxy.rlwy.net:10170/railway

spring.datasource.username=postgres

spring.datasource.password=pEppSsfoePfrPQCJYTQPISbrsWfSPRhl

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# Google OAuth2
spring.ai.openai.api-key=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
spring.ai.openai.base-url=https://openrouter.ai/api/v1
spring.ai.openai.chat.options.model=google/gemini-2.0-flash-exp:free