spring.datasource.url=jdbc:postgresql://postgres-production-16fb.up.railway.app:5432/railway
spring.datasource.username=postgres
spring.datasource.password=pEppSsfoePfrPQCJYTQPISbrsWfSPRhl
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=${PORT:8080}