spring.datasource.url=jdbc:postgresql://shinkansen.proxy.rlwy.net:10170/railway

spring.datasource.username=postgres

spring.datasource.password=pEppSsfoePfrPQCJYTQPISbrsWfSPRhl

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# Google AI / OpenRouter Configuration
spring.ai.openai.api-key=${AI_KEY}
spring.ai.openai.base-url=${AI_URL}
spring.ai.openai.chat.options.model=google/gemini-2.0-flash-exp:free